#!/bin/sh

TIMEOUT=15
QUIET=0
cmdname=$(basename $0)

echoerr() {
  if [ "$QUIET" -ne 1 ]; then printf "%s\n" "$*" 1>&2; fi
}

usage() {
  exitcode="$1"
  cat << USAGE >&2
Usage:
  $cmdname host:port [-t timeout] [-- command args]
  -q | --quiet                        Do not output any status messages
  -shc | --spring-health-check        Check readiness of Spring application by requesting /health method
                                      which provided by Spring Boot Actuator
  -t TIMEOUT | --timeout=timeout      Timeout in seconds, zero for no timeout
  -- COMMAND ARGS                     Execute command with args after the test finishes
USAGE
  exit "$exitcode"
}

wait_for() {
  start_ts=$(date +%s)
  for i in `seq $TIMEOUT` ; do
    if [ $SPRING_HEALTH_CHECK -gt 0 ] ; then
        output=$(curl -s http://${HOST}:${PORT}/health)
        if [[ $output =~ .*\"status\":\"UP\".* ]]; then
           result=0;
        else
           result=1;
        fi
    else
        nc -z "$HOST" "$PORT" > /dev/null 2>&1
        result=$?
    fi
    if [ $result -eq 0 ] ; then
      end_ts=$(date +%s)
      echo "$cmdname: $HOST:$PORT is available after $((end_ts - start_ts)) seconds"
      if [ $# -gt 0 ] ; then
        exec "$@"
      fi
      exit 0
    fi
    sleep 1
  done
  echo "$cmdname: $HOST:$PORT is not available after $TIMEOUT seconds" >&2
  exit 1
}

while [ $# -gt 0 ]
do
  case "$1" in
    *:* )
    HOST=$(printf "%s\n" "$1"| cut -d : -f 1)
    PORT=$(printf "%s\n" "$1"| cut -d : -f 2)
    shift 1
    ;;
    -q | --quiet)
    QUIET=1
    shift 1
    ;;
    -shc | --spring-health-check)
    SPRING_HEALTH_CHECK=1
    shift 1
    ;;
    -t)
    TIMEOUT="$2"
    if [ "$TIMEOUT" = "" ]; then break; fi
    shift 2
    ;;
    --timeout=*)
    TIMEOUT="${1#*=}"
    shift 1
    ;;
    --)
    shift
    break
    ;;
    --help)
    usage 0
    ;;
    *)
    echoerr "Unknown argument: $1"
    usage 1
    ;;
  esac
done

SPRING_HEALTH_CHECK=${SPRING_HEALTH_CHECK:-0}

if [ "$HOST" = "" -o "$PORT" = "" ]; then
  echoerr "Error: you need to provide a host and port to test."
  usage 2
fi

echo "$cmdname: waiting readiness of $HOST:$PORT ..."

wait_for "$@"
